# Generated by Django 5.1.1 on 2024-11-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0005_mbtidescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbtidescription',
            old_name='description',
            new_name='descrição_geral',
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='grupos_de_projetos',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='sala_de_aula',
            field=models.TextField(default=''),
        ),
    ]
