# Generated by Django 5.1.3 on 2024-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0006_rename_description_mbtidescription_descrição_geral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbtidescription',
            old_name='descrição_geral',
            new_name='descricaoGeral',
        ),
        migrations.RenameField(
            model_name='mbtidescription',
            old_name='grupos_de_projetos',
            new_name='gruposDeProjetos',
        ),
        migrations.RenameField(
            model_name='mbtidescription',
            old_name='famous_person_image',
            new_name='pessoaFamosa1',
        ),
        migrations.RenameField(
            model_name='mbtidescription',
            old_name='sala_de_aula',
            new_name='salaDeAula',
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='pessoaFamosa2',
            field=models.ImageField(blank=True, null=True, upload_to='personalities/'),
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='pessoaFamosa3',
            field=models.ImageField(blank=True, null=True, upload_to='personalities/'),
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='subtipo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='tipo',
            field=models.TextField(default=''),
        ),
    ]
