# Generated by Django 5.1.3 on 2024-11-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0007_rename_descrição_geral_mbtidescription_descricaogeral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtidescription',
            name='subtipo',
            field=models.TextField(max_length=46, unique=True),
        ),
        migrations.AlterField(
            model_name='mbtidescription',
            name='tipo',
            field=models.TextField(max_length=46, unique=True),
        ),
    ]
