# Generated by Django 5.1.3 on 2024-11-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0009_alter_mbtidescription_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtidescription',
            name='sidebar_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
