# Generated by Django 5.1.3 on 2024-11-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0010_mbtidescription_sidebar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtidescription',
            name='pessoaFamosa4',
            field=models.ImageField(blank=True, null=True, upload_to='personalities/'),
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='pessoaFamosa5',
            field=models.ImageField(blank=True, null=True, upload_to='personalities/'),
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='pessoaFamosa6',
            field=models.ImageField(blank=True, null=True, upload_to='personalities/'),
        ),
    ]
