# Generated by Django 5.1.3 on 2024-11-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0011_mbtidescription_pessoafamosa4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbtidescription',
            old_name='tipo',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='mbtidescription',
            old_name='subtipo',
            new_name='subclasse',
        ),
    ]
