# Generated by Django 5.1.3 on 2024-12-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0012_rename_tipo_mbtidescription_classe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=3)),
                ('classe', models.CharField(max_length=1)),
            ],
        ),
    ]
