# Generated by Django 5.1.3 on 2024-12-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0013_turmas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.RemoveField(
            model_name='turmas',
            name='classe',
        ),
        migrations.AddField(
            model_name='turmas',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(1, '1º Período'), (2, '2º Período'), (3, '3º Período'), (4, '4º Período'), (5, '5º Período'), (6, '6º Período'), (7, '7º Período'), (8, '8º Período'), (9, '9º Período'), (10, '10º Período')], default='0'),
        ),
        migrations.AddField(
            model_name='turmas',
            name='turma',
            field=models.CharField(choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C')], default='X', max_length=100),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='curso',
            field=models.CharField(choices=[('SI', 'Sistemas de Informação'), ('CC', 'Ciência da Computação'), ('ADS', 'Análise e Desenvolvimento de Sistemas'), ('GTI', 'Gestão da Tecnologia da Informação'), ('Design', 'Design')], max_length=100),
        ),
    ]
