# Generated by Django 5.1.3 on 2024-12-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0014_delete_pessoa_remove_turmas_classe_turmas_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtidescription',
            name='letra1',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='letra2',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='letra3',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mbtidescription',
            name='letra4',
            field=models.CharField(default='', max_length=1),
        ),
    ]
