# Generated by Django 5.1.3 on 2024-12-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0015_mbtidescription_letra1_mbtidescription_letra2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('senha', models.CharField(default='', max_length=8)),
                ('turma', models.CharField(choices=[('SI', 'Sistemas de Informação'), ('CC', 'Ciência da Computação'), ('ADS', 'Análise e Desenvolvimento de Sistemas'), ('GTI', 'Gestão da Tecnologia da Informação'), ('Design', 'Design')], max_length=30)),
                ('periodo', models.PositiveIntegerField()),
            ],
        ),
    ]
