# Generated by Django 5.1.3 on 2024-12-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTypeFlow', '0016_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtidescription',
            name='subtype',
            field=models.CharField(default='', max_length=2),
        ),
    ]
